services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: electronic
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      electronic:
        aliases:
          - database

  core_service:
    build: ./core_service
    container_name: core_service
    env_file:
      - ./core_service/config.env
    ports:
      - "8082:8082"
    depends_on:
      db:
        condition: service_healthy
    networks:
      electronic:
        aliases:
          - core_service

  auth_service:
    build: ./authentication_service
    container_name: auth_service
    env_file:
      - ./authentication_service/config.env
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    networks:
      electronic:
        aliases:
          - auth_service

  authoriz_service:
    build: ./authorization_service
    container_name: autoriz_service
    env_file:
      - ./authorization_service/config.env
    ports:
      - "8083:8083"
    depends_on:
      db:
        condition: service_healthy
    networks:
      electronic:
        aliases:
          - authorization_service

networks:
  electronic:
    driver: bridge
